// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      items: [
        'module1-ros2/index',
        'module1-ros2/architecture',
        'module1-ros2/nodes',
        'module1-ros2/topics-services-actions',
        'module1-ros2/urdf',
        'module1-ros2/launch-files',
        'module1-ros2/rclpy-usage',
        'module1-ros2/ai-integration',
        'module1-ros2/humanoid-control',
        {
          type: 'category',
          label: 'Exercises',
          items: [
            'module1-ros2/exercises/exercise-1',
            'module1-ros2/exercises/exercise-2',
            'module1-ros2/exercises/exercise-3',
            'module1-ros2/exercises/exercise-4',
            'module1-ros2/exercises/assessment',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin Simulation',
      items: [
        'module2-simulation/index',
        'module2-simulation/gazebo-setup',
        'module2-simulation/gazebo-configuration',
        'module2-simulation/urdf-import',
        'module2-simulation/physics',
        'module2-simulation/sensors',
        'module2-simulation/world-building',
        'module2-simulation/unity-setup',
        'module2-simulation/unity-visualization',
        'module2-simulation/unity-ros-connection',
        'module2-simulation/camera-simulation',
        'module2-simulation/lidar-simulation',
        'module2-simulation/imu-simulation',
        'module2-simulation/integration-framework',
        'module2-simulation/motion-testing',
        'module2-simulation/physics-validation',
        'module2-simulation/sensor-connection',
        'module2-simulation/sensor-simulation-exercise',
        'module2-simulation/unity-integration-exercise',
        'module2-simulation/gazebo-exercise',
        'module2-simulation/environment-design-exercise',
        'module2-simulation/debugging-techniques',
        'module2-simulation/custom-environment',
        'module2-simulation/humanoid-physics-config',
        'module2-simulation/module2-completion-summary',
        'module2-simulation/completion-document',
        {
          type: 'category',
          label: 'Module 2 Assessment',
          items: [
            'module2-simulation/module2-assessment',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain',
      items: [
        'module3-ai/index',
        'module3-ai/isaac-sim',
        'module3-ai/isaac-setup',
        'module3-ai/install-configure-isaac',
        'module3-ai/isaac-perception-stack',
        'module3-ai/implement-perception-pipeline',
        'module3-ai/ai-pipeline',
        'module3-ai/vslam',
        'module3-ai/vslam-pipeline',
        'module3-ai/vslam-nav2-integration',
        'module3-ai/nav2-configuration',
        'module3-ai/navigation',
        'module3-ai/sim2real-transfer',
        'module3-ai/jetson-deployment',
        'module3-ai/jetson-deployment-workflow',
        'module3-ai/model-deployment-jetson',
        'module3-ai/motion-planning',
        'module3-ai/implementation-strategies',
        'module3-ai/synthetic-data-setup',
        {
          type: 'category',
          label: 'Exercises',
          items: [
            'module3-ai/exercises/exercise-1',
            'module3-ai/exercises/exercise-2',
            'module3-ai/exercises/exercise-3',
            'module3-ai/exercises/exercise-4',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      items: [
        'module4-vla/index',
        'module4-vla/whisper',
        'module4-vla/whisper-implementation',
        'module4-vla/llm-planning',
        'module4-vla/llm-planner-implementation',
        'module4-vla/task-decomposition',
        'module4-vla/task-decomposition-system',
        'module4-vla/vision-language-integration',
        'module4-vla/integrate-vision-language-systems',
        'module4-vla/vla-architecture',
        'module4-vla/vla-interface-contract',
        'module4-vla/vla-interface-implementation',
        'module4-vla/multi-modal-interaction',
        'module4-vla/multi-modal-interaction-system',
        'module4-vla/gpt-ros2-integration',
        'module4-vla/gpt-ros2-implementation',
        'module4-vla/complete-vla-pipeline',
        {
          type: 'category',
          label: 'Exercises',
          items: [
            'module4-vla/exercises/whisper-integration-exercise',
            'module4-vla/exercises/llm-planning-exercise',
            'module4-vla/exercises/multi-modal-exercise',
            'module4-vla/exercises/vla-system-exercise',
          ],
        },
        'module4-vla/capstone-project',
        {
          type: 'category',
          label: 'Module 4 Assessment',
          items: [
            'module4-vla/assessment',
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;